### ISSUE TITLE
Unable to install gnutls-dev

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [ArchiveTeam/tumblr-grab#62]
I'm unable to install gnutls-dev. It says 
```
The following packages have unmet dependencies: 
libgnutls-dev : Depends: libgnutls30 (= 3.4.10-4ubuntu1.4) but 3.5.18-1ubuntu1 is to be installed 
Depends: libgnutls-openssl27 (= 3.4.10-4ubuntu1.4) but 3.5.18-1ubuntu1 is to be installed 
Depends: libgnutlsxx28 (= 3.4.10-4ubuntu1.4) but 3.5.18-1ubuntu1 is to be installed 
E: Unable to correct problems, you have held broken packages.
```
I'm on Ubuntu Server 18.04.

/etc/apt/sources.list
```
deb http://archive.ubuntu.com/ubuntu bionic main universe
deb http://archive.ubuntu.com/ubuntu bionic-security main universe
deb http://archive.ubuntu.com/ubuntu bionic-updates main universe
```

This causes the error `wget-lua not successfully built`.

**Comment by Engineer-of-Stuff** [comment]
I installed `libgnutls28-dev` instead and the script finished. 
At the end there was an error `./get-wget-lua.sh: line 49: ./wget-lua: Permission denied
`
When I try to start using the archiveteam user (`run-pipeline pipeline.py --concurrent 2 --address '127.0.0.1' nickname`) I get the error 
```
Looking for Wget+Lua in ./wget-lua
('./wget-lua:', OSError(13, 'Permission denied'))
Looking for Wget+Lua in ./wget-lua-warrior
('./wget-lua-warrior:', OSError(2, 'No such file or directory'))
Looking for Wget+Lua in ./wget-lua-local
('./wget-lua-local:', OSError(2, 'No such file or directory'))
Looking for Wget+Lua in ../wget-lua
('../wget-lua:', OSError(2, 'No such file or directory'))
Looking for Wget+Lua in ../../wget-lua
('../../wget-lua:', OSError(2, 'No such file or directory'))
Looking for Wget+Lua in /home/warrior/wget-lua
('/home/warrior/wget-lua:', OSError(2, 'No such file or directory'))
Looking for Wget+Lua in /usr/bin/wget-lua
('/usr/bin/wget-lua:', OSError(2, 'No such file or directory'))
Traceback (most recent call last):
  File "/usr/local/bin/run-pipeline", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/seesaw/script/run_pipeline.py", line 223, in main
    runner = init_runner(args)
  File "/usr/local/lib/python2.7/dist-packages/seesaw/script/run_pipeline.py", line 252, in init_runner
    (project, pipeline) = load_pipeline(args.pipeline, context)
  File "/usr/local/lib/python2.7/dist-packages/seesaw/script/run_pipeline.py", line 39, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 53, in <module>
Exception: No usable Wget+Lua found.
```

I chowned the user's directory but still not working.
